name: Rodar Mercado Livre Ofertas ETL Job Diário

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 9 * * *"

jobs:
  run_etl:
    name: Rodar processo ETL
    runs-on: ubuntu-latest

    steps:
      - name: Clone código
        uses: actions/checkout@v2

      - name: Configurar Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar ETL
        run: python etl/etl.py

      - name: Configurar Git
        run: |
          git config --global user.email "lucasmarchesoni300@gmail.com"
          git config --global user.name "LucasMarchesoni"

      - name: Adicionar arquivos alterados
        run: git add .

      - name: Commit das alterações
        run: git commit -m "Atualização automática do ETL"

      - name: Push para o repositório
        uses: ad-m/github-push-action@v4
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
